-- 创建数据库

CREATE DATABASE mysql_test;

CREATE DATABASE IF NOT EXISTS mysql_test;

CREATE DATABASE IF NOT EXISTS mysql_test DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

-- CREATE DATABASE [IF NOT EXISTS] <数据库名> [[DEFAULT] CHARACTER SET <字符集名>] [[DEFAULT] COLLATE <校对规则名>];
